name: 'CI actions: Build, Lint and Test'

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
    
      - run: pnpm lint:fix

      - run: pnpm build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Upload file to R2
        uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: ${{ secrets.ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.ACCESS_KEY }}
          r2-secret-access-key: ${{ secrets.ACCESS_SECRET_KEY }}
          r2-bucket: ${{ secrets.BUCKET }}
          source-dir: jsonschemas
          destination-dir: ./