name: Publish Package to npmjs
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
          
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: pnpm install
      - run: pnpm build
      - run: |
             echo @lexacode:https://npm.pkg.github.com/ > dist/.npmrc
             echo '//npm.pkg.github.com/:_authToken=${NPM_TOKEN}' >> dist/.npmrc
      - run: pnpm publish --no-git-checks
        working-directory: ./dist
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
